[2025-10-23T17:17:18.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-23T17:17:18.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_crypto_analysis.check_data scheduled__2025-10-22T01:00:00+00:00 [queued]>
[2025-10-23T17:17:18.188+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_crypto_analysis.check_data scheduled__2025-10-22T01:00:00+00:00 [queued]>
[2025-10-23T17:17:18.188+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-10-23T17:17:18.192+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_data> on 2025-10-22 01:00:00+00:00
[2025-10-23T17:17:18.195+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-23T17:17:18.195+0000] {standard_task_runner.py:64} INFO - Started process 477 to run task
[2025-10-23T17:17:18.195+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_crypto_analysis', 'check_data', 'scheduled__2025-10-22T01:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/daily_crypto_analysis_dag.py', '--cfg-path', '/tmp/tmpb01zsdxx']
[2025-10-23T17:17:18.196+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask check_data
[2025-10-23T17:17:18.202+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-23T17:17:18.214+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_crypto_analysis.check_data scheduled__2025-10-22T01:00:00+00:00 [running]> on host a329f6591830
[2025-10-23T17:17:18.243+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_crypto_analysis' AIRFLOW_CTX_TASK_ID='check_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-22T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-22T01:00:00+00:00'
[2025-10-23T17:17:18.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-23T17:17:18.251+0000] {daily_crypto_analysis_dag.py:84} ERROR - ❌ Données insuffisantes : 0 < 1000 enregistrements
[2025-10-23T17:17:18.256+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-23T17:17:18.256+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_crypto_analysis_dag.py", line 86, in check_data_availability
    raise ValueError(error_msg)
ValueError: Données insuffisantes : 0 < 1000 enregistrements
[2025-10-23T17:17:18.260+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_crypto_analysis, task_id=check_data, run_id=scheduled__2025-10-22T01:00:00+00:00, execution_date=20251022T010000, start_date=20251023T171718, end_date=20251023T171718
[2025-10-23T17:17:18.263+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task check_data (Données insuffisantes : 0 < 1000 enregistrements; 477)
[2025-10-23T17:17:18.293+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-23T17:17:18.302+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-23T17:17:18.302+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
